AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  thumbnail_creator

  SAM Template for thumbnail_creator

Globals:
  Function:
    Timeout: 180

Parameters:
  ImageMagickLayer:
    Type: String
    Default: "arn:aws:lambda:us-east-1:<account#>:layer:image-magick:1"
  GhostscriptLayer:
    Type: String
    Default: "arn:aws:lambda:us-east-1:<account#>:layer:ghostscript:1"
  FfmpegLayer:
    Type: String
    Default: "arn:aws:lambda:us-east-1:<account#>:layer:ffmpeg:1"
  ConversionFileType:
    Type: String
    Default: jpg
  ConversionMimeType:
    Type: String
    Default: image/jpeg 
  ThumbnailWidth:
    Type: Number
    Default: 150
  UploadBucket:
    Type: String
    Description: Arn of the UploadBucket
  ResultsBucket:
    Type: String
    Description: Arn of the ResultsBucket

Resources:
  CreateThumbnail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apps/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 2048
      Layers:
        - !Ref ImageMagickLayer
        - !Ref GhostscriptLayer
        - !Ref FfmpegLayer
        - !Ref FileTypeUtils
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref UploadBucket
        - S3WritePolicy:
            BucketName: !Ref ResultsBucket
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref ResultsBucket
          EXTENSION: !Sub '.${ConversionFileType}'
          MIME_TYPE: !Ref ConversionMimeType
          THUMB_WIDTH: !Ref ThumbnailWidth
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*

  FileTypeUtils:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: FileType package
      ContentUri: 'sharedutils/'
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8

Outputs:
  CreateThumbnail:
    Description: "CreateThumbnail Lambda Function ARN"
    Value: !GetAtt CreateThumbnail.Arn
  CreateThumbnailIamRole:
    Description: "Implicit IAM Role created for CreateThumbnail function"
    Value: !GetAtt CreateThumbnailRole.Arn
  UploadBucket:
    Description: "Upload S3 bucket"
    Value: !Ref UploadBucket
  ResultsBucket:
    Description: "Results S3 bucket"
    Value: !Ref ResultsBucket
